#!/usr/bin/env bash

if test "${SSH_AUTH_SOCK}"; then
	ln -sf "${SSH_AUTH_SOCK}" "${HOME}/.ssh/ssh_auth_sock"
fi

if read -r proto cookie && [[ -n "${DISPLAY}" ]]; then
	# X11 forwarding enabled
	if [ "$(echo "${DISPLAY}" | cut -c1-10)" = "localhost:" ]; then
		echo "add unix:$(echo "$DISPLAY" | cut -c11-) $proto $cookie"
	else
		echo "add ${DISPLAY} $proto $cookie"
	fi | xauth -q -
fi
